### ISSUE TITLE
Default values of nested list with items is a spock class.

### ISSUE THREAD

**Issue by gbmarc1** [fidelity/spock#196]
**Describe the bug**
Default values of nested list with items is a spock class.

I think the tested default values are not of the good format in the tests. Thus, the resulting code is not good.

https://github.com/fidelity/spock/blob/80fb2a57f4a99e48932237cf01d356962462c213/tests/base/attr_configs_test.py#L239
https://github.com/fidelity/spock/blob/80fb2a57f4a99e48932237cf01d356962462c213/tests/base/attr_configs_test.py#L285

Should they be respectively?
`nested_list_def: List[NestedListStuff] = [NestedListStuff]`

and

`nested_list_opt_def: Optional[List[NestedListStuff]] = [NestedListStuff]`

I could also want to specify something like that in both cases:

`nested_list_def: List[NestedListStuff] = [NestedListStuff, NestedListStuff(one=1, two="two"), NestedListStuff(one=3, two="four")]`

or

`nested_list_def: List[NestedListStuff] = [NestedListStuff(one=1, two="two"), NestedListStuff(one=3, two="four")]`

I am wondering why `NestedListStuff` works without instantiation because there is no default value for it.

**Comment by ncilfone** [comment]
Right now it's based on string matching to the base class defined within the List annotation. In the current test suite, within the test.yaml file the definition of `NestedListStuff` exists so it gets mapped to that default from the config:

```yaml
NestedListStuff:
    - one: 10
      two: hello
    - one: 20
      two: bye
```

This probably isn't the exact generalizable functionality needed here so a refactor probably is in order to make this more sensible... I'll take a look today

**Comment by ncilfone** [comment]
@gbmarc1 #200 should solve these. Closing
