### ISSUE TITLE
Checking whether an object is an instance of a spock config

### ISSUE THREAD

**Issue by dorukkilitcioglu** [fidelity/spock#48]
**Is your feature request related to a problem? Please describe.**
None

**Describe the solution you'd like**
I want to be able to check whether a Python object is a spock config or not. This will help me distinguish between `dict`, `NamedTuple`, and `spock.config` objects, all of which may contain hyperparameters for different models in a legacy codebase.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by ncilfone** [comment]
A little hack that is used when dynamically creating the attr classes so that they can be pickled correctly (there has to be a class in a module somewhere that pickle can reference):

https://github.com/fidelity/spock/blob/3efd1a48cf5885fe793828da397a61582b2a50ed/spock/backend/attr/config.py#L49

This means that all `@spock` wrapped classes end up in sys.modules['spock'].backend.attr.config when code/a script is running.

Thus I think the simple solution here is to check the both the module location of the cls using `cls.__module__` and `attr.has()` to verify it is a class with attrs attributes. This would prevent all attr classes from being True on a method and instead only those that are registered within the spock module.
